@baseUrl = http://localhost:3000/activite
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxNjc5MTg5NCwiZXhwIjoxNzE2ODc4Mjk0fQ.fWpoI0-UkUoFXKpRc6IrHPfwzeAbO3iIbYIjyEBA_Hk

###
POST {{baseUrl}}/onRuche
Content-Type: application/json
Authorization: bearer {{authToken}}

{
    "description": "description de l'activité",
    "dateTime": "2024-05-20T00:45:30Z",
    "fkCategorie": 2,
    "fkRucheOrRucher": 6
}

###
POST {{baseUrl}}/onRucher
Content-Type: application/json
Authorization: bearer {{authToken}}

{
    "description": "description de l'activité",
    "dateTime": "2024-05-20T00:45:30Z",
    "fkCategorie": 2
}


###
GET {{baseUrl}}
Authorization: bearer {{authToken}}

###
GET {{baseUrl}}/year/2024
Authorization: bearer {{authToken}}

###
GET {{baseUrl}}/2 

###
PATCH {{baseUrl}}/2
Content-Type: application/json

{
    "description": "Nouvelle description"
}

###
DELETE {{baseUrl}}/13
Authorization: bearer {{authToken}}