@baseUrl = http://localhost:3000/activite
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxNjU0MzI4MCwiZXhwIjoxNzE2NjI5NjgwfQ.wP3BAVuCXBykdxyqXJrSfbcGHHaHBl43fHc7p83p7GE

###
POST {{baseUrl}}/onRuche
Content-Type: application/json
Authorization: bearer {{authToken}}

{
    "description": "description de l'activité",
    "dateTime": "2024-05-20T00:45:30Z",
    "fkCategorie": 2,
    "fkRucheOrRucher": 6
}

###
POST {{baseUrl}}/onRucher
Content-Type: application/json
Authorization: bearer {{authToken}}

{
    "description": "description de l'activité",
    "dateTime": "2024-05-20T00:45:30Z",
    "fkCategorie": 2,
    "fkRucheOrRucher": 1
}


###
GET {{baseUrl}}
Authorization: bearer {{authToken}}

###
GET {{baseUrl}}/year/2024

###
GET {{baseUrl}}/2 

###
PATCH {{baseUrl}}/2
Content-Type: application/json

{
    "description": "Nouvelle description"
}

###
DELETE {{baseUrl}}/13
Authorization: bearer {{authToken}}