@baseUrl = http://localhost:3000/auth 
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxNjM4MzA0NCwiZXhwIjoxNzE2NDY5NDQ0fQ.gLX3GvZDarS3Wu9EeXlq-f1g1WsKOk-HYeR7rMY1RAk

### 
POST {{baseUrl}}/register 
Content-Type: application/json

{

    "username": "kevin", "password": "1234"

}

### 
POST {{baseUrl}}/login 
Content-Type: application/json

{

    "username": "kevin", "password": "1234"

}

### 
GET {{baseUrl}}/verify 
Authorization: bearer {{authToken}}
