@baseUrl = http://localhost:3000/auth 
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxNjM1OTQ5MywiZXhwIjoxNzE2MzYzMDkzfQ.OqNnfbdKK6VLK4t_bEd-1UiT9Fk6U-t2eyS1wy6Fkxc

### 
POST {{baseUrl}}/register 
Content-Type: application/json

{

    "username": "kevin", "password": "1234"

}

### 
POST {{baseUrl}}/login 
Content-Type: application/json

{

    "username": "kevin", "password": "1234"

}

### 
GET {{baseUrl}}/verify 
Authorization: bearer {{authToken}}
