@baseUrl = http://localhost:3000/categorie

@authToken = empty

###
POST {{baseUrl}}
Content-Type: application/json

{
    "name": "nourrissement"
}

###
GET {{baseUrl}}

###
GET {{baseUrl}}/1 

###
DELETE {{baseUrl}}/1