@baseUrl = http://localhost:3000/reine

@authToken = empty

###
POST {{baseUrl}}
Content-Type: application/json

{
    "birthYear": 2022,
    "fkCouleur": 2
}

###
GET {{baseUrl}}

###
GET {{baseUrl}}/2

###
DELETE {{baseUrl}}/1