@baseUrl = http://localhost:3000/rucher

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxNjM1OTQ5MywiZXhwIjoxNzE2MzYzMDkzfQ.OqNnfbdKK6VLK4t_bEd-1UiT9Fk6U-t2eyS1wy6Fkxc

###
POST {{baseUrl}}
Content-Type: application/json

{
    "nbr": 2345,
    "name": "Rucher de Kevin",
    "localisation": "Rue des ruches, 1024 Lausanne",
    "fkApiculteur": 2
}

###
GET {{baseUrl}}

###
GET {{baseUrl}}/1

###
GET {{baseUrl}}/1/ruches

###
GET {{baseUrl}}/1/activites
Authorization: bearer {{authToken}}

###
PATCH {{baseUrl}}/2
Content-Type: application/json

{
    "name": "Les Ruchers de kevin"
}

###
DELETE {{baseUrl}}/2