@baseUrl = http://localhost:3000/ruche

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcxNjM1OTQ5MywiZXhwIjoxNzE2MzYzMDkzfQ.OqNnfbdKK6VLK4t_bEd-1UiT9Fk6U-t2eyS1wy6Fkxc

###
POST {{baseUrl}}
Content-Type: application/json

{
    "nbr": 1203,
    "description": "2ème ruche de kevin",
    "fkReine": 2,
    "fkRucher": 1,
    "fkCouleur": 2
}

###
GET {{baseUrl}}

###
GET {{baseUrl}}/3

###
GET {{baseUrl}}/7/activites
Authorization: bearer {{authToken}}

###
PATCH {{baseUrl}}/2
Content-Type: application/json

{
    "description": "La super ruche de Kevin"
}

###
DELETE {{baseUrl}}/2