@baseUrl = http://localhost:3000/ruche

@authToken = empty

###
POST {{baseUrl}}
Content-Type: application/json

{
    "nbr": 1203,
    "description": "2ème ruche de kevin",
    "fkReine": 2,
    "fkRucher": 1,
    "fkCouleur": 2
}

###
GET {{baseUrl}}

###
GET {{baseUrl}}/3

###
GET {{baseUrl}}/3/activites

###
PATCH {{baseUrl}}/2
Content-Type: application/json

{
    "description": "La super ruche de Kevin"
}

###
DELETE {{baseUrl}}/2