# Stage 1: Build the Vue.js app
FROM node:16-alpine as build-stage

# Set the working directory
WORKDIR /app

# Copy the app directory and install dependencies
COPY app/package*.json ./
RUN npm install

# Copy the rest of the app files and build
COPY app/ ./
RUN npm run build

# Stage 2: Set up the Node.js server
FROM node:16-alpine

# Set the working directory
WORKDIR /server

# Copy the server directory and install dependencies
COPY server/package*.json ./
RUN npm install

# Copy the rest of the server files
COPY server/ ./

# Copy the .env file if it exists
COPY server/.env ./

RUN npx prisma generate

# Copy the built Vue.js app from the previous stage
COPY --from=build-stage /app/dist ./public

# Expose the port that your Node.js app uses
EXPOSE 3000

# Start the Node.js server
CMD ["npm", "run", "start"]